Service to service authorization
smartworldteam/egal-framework-php-package pull request #10
Opened 2021-05-20 09:44 UTC by l-max

2021-05-21 06:38 UTC, rollsover requested changes

2021-05-21 06:38 UTC, rollsover commented on model/Metadata/ModelActionMetadata.php
> +     * @throws \ReflectionException
clean up?

2021-05-21 06:38 UTC, rollsover commented on core/Session/Session.php
> -            throw new CurrentSessionException('The current Session does not contain ActionMessage!');
Почему убрано? В сессии, если это не демон обработки, может не быть сообщения действия

2021-05-21 06:38 UTC, rollsover commented on auth/Tokens/ServiceMasterToken.php
> +    public static function fromArray(array $array): Token
Возвращается SMT

2021-05-21 06:38 UTC, rollsover commented on core/ActionCaller/ActionCaller.php
> +    {
isServiceAccess есть проверка на наличие корректного токена, а тут нет, вочему?

2021-05-21 06:38 UTC, rollsover commented on core/Communication/Request.php
> +        }
А если человек захочет оправить с другим токеном? Допустим с токеном пользователя

2021-05-21 06:38 UTC, rollsover commented on core/Session/Session.php
> +     * @throws \Egal\Auth\Exceptions\InitializeUserServiceTokenException
Clean up?

2021-05-21 06:38 UTC, rollsover commented on core/Session/Session.php
> +     * @throws \Egal\Auth\Exceptions\TokenExpiredException
clean up?

2021-05-21 06:38 UTC, rollsover commented on core/Session/Session.php
> +     * @throws \Egal\Auth\Exceptions\TokenExpiredException
clean up?

2021-05-21 06:56 UTC, l-max commented on model/Metadata/ModelMetadata.php
> +                    throw new Exception('Все actions должны быть статичными методами!');
It's strange merge. Anyway I fixed it.

2021-05-21 06:56 UTC, l-max commented on model/Metadata/ModelMetadata.php
> +        throw new Exception($actionName . ' не существует в модели ' . $this->modelClass . '!');
It's strange merge. Anyway I fixed it.

2021-05-21 06:58 UTC, l-max commented on core/ActionCaller/ActionCaller.php
> +    {
fixed

2021-05-21 07:00 UTC, l-max commented on core/Communication/Request.php
> +        }
Не уверен что это будет нужно, но можно заложить такую возможность.

2021-05-21 07:10 UTC, l-max commented on model/Metadata/ModelActionMetadata.php
> +     * @throws \ReflectionException
nope

2021-05-21 07:16 UTC, l-max commented on core/Session/Session.php
> -            throw new CurrentSessionException('The current Session does not contain ActionMessage!');
Метод удалил а внутренности перенес в единственное место где это использовалось (getServiceServiceToken())
В этом методе не было смысла.

2021-05-21 07:23 UTC, l-max commented on auth/Tokens/ServiceMasterToken.php
> +    public static function fromArray(array $array): Token
done

2021-05-24 04:46 UTC, rollsover approved these changes

2021-05-24 04:47 UTC, merged