Feature: And, or operators in action accesses.
smartworldteam/egal-framework-php-package pull request #18
Opened 2021-06-06 17:08 UTC by rollsover

2021-06-08 05:41 UTC, l-max requested changes

2021-06-08 07:48 UTC, rollsover commented on model/Metadata/ModelActionMetadata.php
> +     * @throws ReflectionException
Исправлено

2021-06-08 07:51 UTC, rollsover commented on model/Metadata/ModelActionMetadata.php
> +    private const OR_TAG_SEPARATOR = '|';
Исправлено

2021-06-08 07:55 UTC, rollsover commented on model/Metadata/ModelActionMetadata.php
> +            break;
Исправлено, почему-то phpstorm хотел так)

2021-06-08 07:57 UTC, rollsover commented on model/ModelManager.php
> +     * @noinspection PhpUnused
Исправлено

2021-06-10 07:52 UTC, l-max approved these changes

2021-06-10 07:52 UTC, merged